### ISSUE TITLE
Asset uploading to wrong asset folder

### ISSUE THREAD

**Issue by strohrdanz** [roundhouse/FormBuilder-2-Craft-CMS#137]
I have my field set to the correct asset source, but it's uploading files submitted through the form to a the first asset source. Not sure why.

**Comment by alexr8** [comment]
I'm getting the same issue - files do not get uploaded to the file location specified in the assets field.

**Comment by owldesign** [comment]
fixed, verify?

**Comment by alexr8** [comment]
I've downloaded and tested 2.0.20. I can't seem to find the uploaded the asset in any of my asset sources, and trying the 'download all' button throws a 500 error. Before, the asset was uploaded to the wrong asset source, but now it doesn't appear in any asset sources.

**Comment by owldesign** [comment]
i'll troubleshoot

**Comment by steveooo9** [comment]
@owldesign @vadim-rh I fixed this issue we had for some time. The issue was that a wrong method was used to get a folder. So if `sourceId` and  `folderId` were used the wrong way. Now everything works here. Also it prevents some other bug if the asset field doesn't have the option "only in this folder" set.

Could you please add this and issue a release(.json)? Thanks!

[FormBuilder2_EntryController.php.zip](https://github.com/roundhouse/FormBuilder-2-Craft-CMS/files/2962655/FormBuilder2_EntryController.php.zip)

**Comment by steveooo9** [comment]
Would be great if this get's a quick fix. My attached code works fine in production (after 9 days of testing)

**Comment by owldesign** [comment]
@steveooo9 ok updated and pushed up to latest, thanks for the work!
