### ISSUE TITLE
Relative logo url in template

### ISSUE THREAD

**Issue by marknotton** [roundhouse/FormBuilder-2-Craft-CMS#142]
When emails come through, the logo in the head of the template is using a relative URL for the  image. I think there needs to be a check to ensure it include the full absolute URL. 

In my project, the siteUrl in defined correctly. I'm using version 2.0.19. 

Temporarily I've amended line 83 of `templates/email/layouts/html.twig` to this:

`<img src="{{ siteUrl }}{{ logo.getUrl() }}" style="max-width: 100%; margin-top: 10px; margin-bottom: 20px;" alt="{{ logo.slug }}" border="0">
`

It's not elegant, but it does the trick for now.

**Comment by owldesign** [comment]
@marknotton works fine here. There url gets built with [this function](https://github.com/craftcms/cms/blob/master-v2/src/helpers/AssetsHelper.php#L57-L65). 

Notice that its appending `$baseUrl = $sourceType->getBaseUrl();`

So you need to make sure that your Asset Source's  `URL` actually has the absolute url structure.. ex `http://yoursite.com/file/system/path` and not just `/file/system/path`

Im closing this since `getUrl()` will create absolute path if its setup correctly within your Asset Source settings.
