### ISSUE TITLE
If possible to send notification to different email based on a input field result

### ISSUE THREAD

**Issue by daituzhang** [roundhouse/FormBuilder-2-Craft-CMS#39]
Hi,
Sorry to bother you again.
Just like I mentioned on the title, is it possible to have the notification to different email address dynamically on submission or maybe generated custom subject line based on their input?

Thank you!

**Comment by owldesign** [comment]
Do you mean like if you had a select drop down field with options such as 
`<select>`
`<option value="support@company.com">Customer Support</option>`
`<option value="product@company.com">Product Inquiry</option>`
`<option value="hello@company.com">General Inquiry</option>`
`</select>`
it would send to whichever user picked?

I think it might be easier to just go the custom generated subject line. Basically during form setup you can select a field (in this case it can be a select dropdown if you have specific subjects you want user to pick from) that will act as a subject line. 

Of course please let me know if any of these what you were thinking?

**Comment by daituzhang** [comment]
Yes exactly!

Custom generated subject line will work on my case as well. Do you have any suggestions on that?

Great thanks!!!

**Comment by owldesign** [comment]
I'll build an option into form setup that'll let you pick a field that will act as the subject or if there isn't one selected it'll use default subject line

**Comment by owldesign** [comment]
@daituzhang when you get a change pull master, I have added this functionality in.

![screen shot 2016-03-25 at 1 04 45 pm](https://cloud.githubusercontent.com/assets/438764/14052806/2b849448-f28a-11e5-8916-a418fb8407e5.png)

However in order to see this Custom Subject toggle your form must first have fields added to it. So if you're creating a new form, add fields first, save it and go back to edit it and this toggle will show up.

Let me know if you have any questions.

**Comment by daituzhang** [comment]
Thank you soooooooooo much! I'm trying to add a new field. Sorry that maybe I should open a new issue, but since there are no longer custom form fields, how the `type` attr being added, is it possible to make them email or all int for html5 input validation? Also is there any js validation lib still available?
Great thanks!!

**Comment by owldesign** [comment]
You can follow this to create you own input markup https://github.com/roundhouse/FormBuilder-2-Craft-CMS#custom-fields-html-markup 

However, I don't think that will hep you since changing `type="text"` to `type="email"` will change it to all the text fields in the form.  I think I'm going to add more options for the fields. There are few new html5 input types I'd like to add such as email, number, range, etc..

I don't have built in js validation for this plugin, just server side if the fields are required. I'm leaving it up to you guys to add your own js validation. http://parsleyjs.org/ can be easily set up. Or follow instructions

**Comment by daituzhang** [comment]
Hi @owldesign Thank you so much for adding on the functionality! It works really good!
