### ISSUE TITLE
Failed submission due to non existent mail address still sent as notification to admin.

### ISSUE THREAD

**Issue by noregt** [roundhouse/FormBuilder-2-Craft-CMS#79]
When I test the form with a nonexistent mail address, for instance 'asdfasdf' (so without @ or .com), the administrator still receives this as a notification even though there's a system error.

**Comment by owldesign** [comment]
This sounds like the expected functionality. You have admin notifications setup so they admin will get the email because the email is set in the settings. However, submitter will not get the email because they are entering incorrectly formatted email address thus why it breaks. 

I don't have custom email fields in my plugins.
You have two options.
#1 Sprout Field - http://sprout.barrelstrengthdesign.com/craft-plugins/fields 
#2 Custom Templates - https://github.com/roundhouse/FormBuilder-2-Craft-CMS#custom-fields-html-markup
