### ISSUE TITLE
Custom HTML for form

### ISSUE THREAD

**Issue by cibgraphics** [roundhouse/FormBuilder-2-Craft-CMS#9]
I am needing custom HTML for my form that just looping through the fields doesn't allow me to do.  Is there a way to call a singular form input?

I don't see anything in the documentation on how to do it.

**Comment by owldesign** [comment]
I don't have this option, will be looking into adding in the future.

**Comment by InigoWD** [comment]
I have the same problem- one of my text inputs is different to the others and requiries different markup. Amazing that this is beyond the bounds of the plugin...

**Comment by owldesign** [comment]
@cibgraphics @InigoWD I have added ability to add custom templates. During the loop it will check if the field has a custom template and if does it will use that instead of default once.

In your form `Fields` tab you have another option for `Custom Template` when you click the settings icon next to your field.

Place your templates in `craft/templates` folder.

Blue border to the left of your field indicates that a custom template has been assigned to that field.

Let me know if any issues/questions

![screen shot 2016-08-04 at 2 16 55 pm](https://cloud.githubusercontent.com/assets/438764/17418585/1da3e578-5a4e-11e6-96fb-c1378574ecd0.png)

**Comment by lexbi** [comment]
@owldesign Can we still override the standard fields with a custom folder somehow? I would still like to customise the normal text field for example, but, I don't want to set a custom template for every field in the backend.

**Comment by owldesign** [comment]
@lexbi The custom folder way isn't there anymore. You'd have to update every field's Custom Template to your custom text field. I guests if you have a bunch of fields it would be extra work to go back and set Custom Template routes but this change is good!

**Comment by lexbi** [comment]
Is there any way you could bring it back? 
It's nice to have the option of both, I really like that you have added this option because it lets you do specific fields very easily. 
BUT, as an example I have a form with like 10 text fields (I don't mind in this case but it's just an example), it's a bit annoying to add custom templates to each one especially when it's something simple like adding a `*` to a required field's label, and, if a client ever wanted to add a field, they wouldn't have a clue what to do here!

**Comment by owldesign** [comment]
Ok I can provide two options

**Comment by StevenVerbiest** [comment]
@owldesign Did you reimplement the 'old' option? Or is overriding each fields template the only way of setting custom html?
