### ISSUE TITLE
Cannot delete submission if CSRF enabled

### ISSUE THREAD

**Issue by benjo696** [roundhouse/FormBuilder-2-Craft-CMS#96]
Could we please have a CSRF check on the delete submission form.

**Comment by owldesign** [comment]
I have added this in place, master up to date. Thanks!

**Comment by frankpapenmeier** [comment]
I encountered the same error with current master.

It turned out that your commit from  Jan 11, 2017 did not solve the issue because it adds the original CSRF and not current CSRF to the delete form.

Doing the following resolved the issue for me:

In file templates/entries/_view.twig

REPLACE
```
{% if submission.CRAFT_CSRF_TOKEN is defined %}
<input type="hidden" name="CRAFT_CSRF_TOKEN" value="{{ submission.CRAFT_CSRF_TOKEN }}">
{% endif %}
```
WITH
`{{ getCsrfInput() }}`

**Comment by owldesign** [comment]
@frankpapenmeier I made the update, thanks. Will be fixed on next push.
